// Moved to @bb/client-core (shared with the native app); re-exported here so web imports keep resolving.
export {
  shouldQueueFollowUpMessage,
  buildFollowUpSubmitMode,
  buildSideChatSubmitMode,
  canSubmitFollowUpShortcut,
  resolveDefaultExecutionOptionsState,
  buildAutoFollowUpRequest,
  buildCreateQueuedFollowUpRequest,
  buildSendQueuedMessageByIdRequest,
  buildFollowUpShortcutRequest,
} from "@bb/client-core";
export type {
  SendMessageMutationRequest,
  CreateQueuedFollowUpRequest,
  SendQueuedMessageByIdRequest,
  ThreadExecutionSelection,
  FollowUpExecutionSelection,
  BuildAutoFollowUpRequestArgs,
  BuildCreateQueuedFollowUpRequestArgs,
  BuildSendQueuedMessageByIdRequestArgs,
  BuildFollowUpShortcutRequestArgs,
  CanSubmitFollowUpShortcutArgs,
  BuildFollowUpSubmitModeArgs,
  BuildSideChatSubmitModeArgs,
  ResolveDefaultExecutionOptionsStateArgs,
  QueuedMessageForSend,
  FollowUpShortcutRequest,
  DefaultExecutionOptionsState,
} from "@bb/client-core";
