import type { Href } from "expo-router";

/**
 * Href builders for the routes the shell still owns.
 *
 * The page owns every product surface, so this is a short list: the WebView
 * itself, the device settings that can turn it off, server profiles, and
 * connect enrolment. A page path travels inside `webViewShellHref`, never as a
 * native route.
 *
 * Typed routes (`.expo/types/router.d.ts`) are generated by Metro from the
 * `app/` tree, so they lag behind route files that other screens add in the
 * same change and are absent entirely in CI. `untypedHref` is the single
 * place that crosses that boundary; every builder below funnels through it.
 */
type HrefParams = Record<string, string | undefined>;

function untypedHref(pathname: string, params?: HrefParams): Href {
  const definedParams = params
    ? Object.fromEntries(
        Object.entries(params).filter(
          (entry): entry is [string, string] => entry[1] !== undefined,
        ),
      )
    : undefined;
  const href: { pathname: string; params?: Record<string, string> } = {
    pathname,
    ...(definedParams && Object.keys(definedParams).length > 0
      ? { params: definedParams }
      : {}),
  };
  // Typed-route boundary (see the module comment).
  return href as Href;
}

/** The first value of an expo-router search param, trimmed ("" when absent). */
export function firstParam(value: string | string[] | undefined): string {
  const raw = Array.isArray(value) ? value[0] : value;
  return raw?.trim() ?? "";
}

/**
 * A mobile route path that was computed outside the builders (the deep-link
 * resolver's `next` path after adding a server). Same typed-route boundary.
 */
export function rawPathHref(path: string): Href {
  return path as Href;
}

/**
 * The WebView shell (`/webview`): one screen that renders the page for a
 * profile. `path` is a page path, not a mobile route.
 */
export function webViewShellHref(
  params: { profileId?: string; path?: string } = {},
): Href {
  return untypedHref("/webview", {
    profileId: params.profileId,
    path: params.path,
  });
}

interface ConnectEnrollHrefParams {
  code?: string;
  serverUrl?: string;
  apex?: string;
  /** Re-pair an existing connect profile (revoked credential). */
  profileId?: string;
}

/** bb connect enrollment (`/connect`; also the `bb://connect?code=…` deep link). */
export function connectEnrollHref(params: ConnectEnrollHrefParams = {}): Href {
  return untypedHref("/connect", {
    code: params.code,
    serverUrl: params.serverUrl,
    apex: params.apex,
    profileId: params.profileId,
  });
}

/** The server list this phone keeps (`/settings/servers`). */
export function serversHref(): Href {
  return untypedHref("/settings/servers");
}

type SettingsSectionRoute = "device" | "appearance";

/** One of the shell's own settings screens. */
export function settingsSectionHref(section: SettingsSectionRoute): Href {
  return untypedHref(`/settings/${section}`);
}
