// Moved to @bb/client-core (shared with the native app); re-exported here so web imports keep resolving.
export {
  createFilePreviewLineRange,
  areFilePreviewLineRangesEqual,
  getFilePreviewLineRangeStart,
  areEnvironmentFilePreviewSourcesEqual,
  isHtmlFilePreviewPath,
  normalizeFilePreviewMimeType,
  isMarkdownFilePreview,
  isCsvFilePreview,
  buildFilePreview,
} from "@bb/client-core";
export type {
  FilePreviewTarget,
  ImageFilePreview,
  VideoFilePreview,
  TextFilePreview,
  UnsupportedFilePreview,
  FilePreview,
  EnvironmentFilePreviewSource,
  WorkspaceFilePreviewStatusLabel,
  FilePreviewLineRange,
  CreateFilePreviewLineRangeArgs,
  AreFilePreviewLineRangesEqualArgs,
  GetFilePreviewLineRangeStartArgs,
  WorkspaceFileTabState,
  HostFileTabState,
  ThreadStorageFileTabState,
  BuildFilePreviewArgs,
} from "@bb/client-core";
