// Moved to @bb/client-core (shared with the native app); re-exported here so web imports keep resolving.
export {
  isWorkspaceFilePreviewTab,
  isStorageFilePreviewTab,
  isBrowserTab,
  isNewTab,
  isSecondaryFileTab,
  isFixedPanelViewTab,
  reconcileFixedPanelViewTabsInState,
  getActiveSecondaryPanelTab,
  findSecondaryPanelTab,
  setSecondaryPanelTabsInState,
  upsertSecondaryPanelTab,
  removeSecondaryPanelTab,
  openSecondaryPanelTabInState,
  replaceNewTabWithSecondaryPanelTabInState,
  updateSecondaryPanelTabInState,
  activateSecondaryPanelTabInState,
  closeSecondaryPanelTabInState,
  reorderSecondaryPanelFileTabInState,
  clearActiveSecondaryFileTabInState,
  removeWorkspaceTabsForOtherEnvironments,
  pruneStorageTabs,
  getActiveTabIdAfterPrune,
  buildOrderedSecondaryPanelFileTabs,
} from "@bb/client-core";
